### ISSUE TITLE
Compatibility with chat UIs (BetterChatGPT)

### ISSUE THREAD

**Issue by chitudorin** [chand1012/openai-cf-workers-ai#3]
I succesfully deployed the worker and confirmed it does work with [OpenAI's API reference examples](https://platform.openai.com/docs/api-reference/chat) but running a [fork](https://github.com/chitudorin/chitudorin.github.io) of [BetterChatGPT](https://github.com/ztjhz/BetterChatGPT) (in order to permit newer models) does not work.  

Running log stream on my worker returns a 404 error and it looks like the request is an OPTIONS one, instead of GET.

**Comment by chand1012** [comment]
Okay that means that CORS is definitely the issue. That's definitely a bug, I'll see what I can do.

**Comment by chand1012** [comment]
Can you try deploying with the branch `cors`? I made a change that should fix that issue. Its the same branch as PR #4.

**Comment by chitudorin** [comment]
I tried deploying it but there are some build errors:

```
$ yarn deploy
yarn run v1.22.22
$ wrangler deploy index.js
 ⛅ wrangler 3.37.0
-------------------

✘ [ERROR] No matching export in "node_modules/itty-router/dist/itty-router.min.mjs" for import "createCors"

    index.js:1:17:
      1 │ import { Router, createCors, error, json } from 'itty-router';
        ╵                  ~~~~~~~~~~


✘ [ERROR] No matching export in "node_modules/itty-router/dist/itty-router.min.mjs" for import "error"

    index.js:1:29:
      1 │ import { Router, createCors, error, json } from 'itty-router';
        ╵                              ~~~~~


✘ [ERROR] No matching export in "node_modules/itty-router/dist/itty-router.min.mjs" for import "json"

    index.js:1:36:
      1 │ import { Router, createCors, error, json } from 'itty-router';
        ╵                                     ~~~~


✘ [ERROR] Build failed with 3 errors:

  index.js:1:17: ERROR: No matching export in "node_modules/itty-router/dist/itty-router.min.mjs"
  for import "createCors"
  index.js:1:29: ERROR: No matching export in "node_modules/itty-router/dist/itty-router.min.mjs"
  for import "error"
  index.js:1:36: ERROR: No matching export in "node_modules/itty-router/dist/itty-router.min.mjs"
  for import "json"

```

**Comment by chand1012** [comment]
Sorry about that! Forgot to update `itty-router` in the package file. Not sure why it built locally, but its fixed to be the latest version now.

**Comment by chitudorin** [comment]
It builds successfully now, but now it returns 500:

```
{
    "status": 500,
    "error": "Cannot read properties of undefined (reading 'AI')"
}
```

This is the request body:

```
{
   "messages":[
      {
         "role":"system",
         "content":"You are ChatGPT, a large language model trained by OpenAI.\nCarefully heed the user's instructions. \nRespond using Markdown."
      },
      {
         "role":"user",
         "content":"hi"
      }
   ],
   "model":"@cf/meta/llama-2-7b-chat-int8",
   "temperature":1,
   "presence_penalty":0,
   "top_p":1,
   "frequency_penalty":0,
   "stream":true
}
```

Is there anything I should remove/add from/to the request body?

**Comment by chand1012** [comment]
No that was my bad again, fixed with the latest commit. If you're curious as to what I screwed up it was this: 6cb8425f9f100dd7fb0c065d4f06ffe05a8fee79.

**Comment by chitudorin** [comment]
Actually, the API reference response has a trailing comma after the content. I'll see if that's relevant enough to work.

https://platform.openai.com/docs/api-reference/chat/create

**Comment by chitudorin** [comment]
I think BetterChatGPT [only accepts streaming responses](https://github.com/ztjhz/BetterChatGPT/issues/290#issuecomment-1547255077) so since Cloudflare's isn't it's not processing it at all.

**Comment by chand1012** [comment]
Streaming responses are on my list of todos but I have no ETA.

**Comment by chand1012** [comment]
@chitudorin quick update on this, as of PR #5, streaming is now supported on the main branch.

**Comment by chitudorin** [comment]
@chand1012 I randomly checked the repo like 10 hours ago and saw the PR. Tested it then and confirmed it works, nice!
