### ISSUE TITLE
[BUG] Image generation dose not work

### ISSUE THREAD

**Issue by boixu** [chand1012/openai-cf-workers-ai#9]
Hi

What ever I try I am unable to get the image generation to work.

Always receive the following error 
`{"error":"Provided readable stream must have a known length (request/response body or readable half of FixedLengthStream)"}`
R2 bucket has been created.
I am using curl to make the request and took the OpenAI image generation as an example.
Example used with redacted info
`curl -L https://openai-cf.example.workers.dev/v1/images/generations \
                                                                -H "Content-Type: application/json" \
                                                                -H "Authorization: Bearer xxxxxxxxxxxxxxxx" \
                                                                -d '{
                                                          "model": "@cf/stabilityai/stable-diffusion-xl-base-1.0",
                                                          "prompt": "A cute baby sea otter",
                                                          "n": 1,
                                                          "size": "1024x1024"
                                                        }'` 
                                                        
Any and all help is appreciated!
Thanks!

**Comment by boixu** [comment]
Was able to fix it by editing the routes/image.js file

**Comment by boixu** [comment]
Created pull request with fixes that solved the issue for me :)
Fix #10

**Comment by eric2788** [comment]
@chand1012 Is this repo still under-maintained? I got `KeyError: 'b64_json'` when using image generation

**Comment by eric2788** [comment]
> [@chand1012](https://github.com/chand1012) Is this repo still under-maintained? I got `KeyError: 'b64_json'` when using image generation

I know why, open web UI is using response_format instead of format, I may fork one to fix then

![Image](https://github.com/user-attachments/assets/88b584e2-d62e-4088-ac06-ef0dd9f7ca9a)

**Comment by chand1012** [comment]
Hello @eric2788, if you make a PR fixing the issue I will merge it in as soon as I verify it works.
